version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.5
    environment:
      - node.name=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml://usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.5
    ports:
      - "5601:5601"

  logstash:
    build: 
      context: ./logstash
    environment:

     - LS_NODE_NAME=ls01
    links:
    - elasticsearch
    volumes:
    - "./logstash/pipeline/:/usr/share/logstash/pipeline/"
    - "./logstash/conf/log4j2.properties:/usr/share/logstash/config/log4j2.properties"
    - "./logstash/conf/logstash.yml:/usr/share/logstash/config/logstash.yml"
    - "./logstash/conf/pipelines.yml:/usr/share/logstash/config/pipelines.yml"
    - "./logstash/queue/:/tmp/queue"
    - "./logstash/lookup_data/:/tmp/logstash/jdbc_static/import_data"
    - "./logstash/drivers/postgresql-42.2.8.jar:/tmp/logstash/vendor/postgresql-42.2.8.jar"
    - "./logstash/data:/usr/share/logstash/data"
    depends_on:
    - elasticsearch
    command: --config.reload.automatic
    

volumes:
  es_data:
    driver: local

networks:
  default:
    external:
      name: lspoc