version: '3.1'

services:

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lspoc.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5431:80

volumes:
  data:
    driver: local

networks:
  default:
    external:
      name: lspoc